name: Docker Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 2'

jobs:

  build:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      tags: "serversideup/certbot-dns-cloudflare:latest"
    secrets: inherit

  update_container_readme:
    runs-on: ubuntu-20.04
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/certbot-dns-cloudflare
          provider: dockerhub
          short_description: 'A simple wrapper around certbot/dns-cloudflare to add a renewal interval.'
          readme_file: 'README.md'